BEGIN;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM pos_merchant_permission_audit LIMIT 1) THEN RAISE EXCEPTION 'REFUSE_101_ROLLBACK_PERMISSION_AUDIT_EXISTS'; END IF;
END $$;
DROP TABLE pos_merchant_permission_audit;
COMMIT;
