import {useState} from 'react';
import {rupiah,storeApi} from './storeApi';
import './merchantWorkspace.css';

const sections=[['home','Beranda','profile.read'],['sell','Kasir','sale.post'],['products','Produk & Stok','products.read'],['customers','Customer','customers.read'],['suppliers','Supplier & Pembelian','purchases.post'],['finance','Keuangan','money.manage'],['debts','Utang & Piutang','reports.read'],['reports','Laporan','reports.read'],['online','Online Store','orders.read'],['users','Pengguna & Akses','users.manage'],['settings','Pengaturan','profile.manage']];
const moneyKinds=[['CAPITAL','Modal'],['OTHER_INCOME','Pendapatan lain'],['EXPENSE','Biaya operasional'],['WITHDRAWAL','Prive'],['TRANSFER','Transfer']];
const uid=()=>crypto.randomUUID();
export default function MerchantWorkspacePage(){
 const [auth,setAuth]=useState(null),[login,setLogin]=useState({login:'',password:'',businessId:''}),[section,setSection]=useState('home'),[data,setData]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[form,setForm]=useState({});
 const call=(path,options={})=>storeApi(`/pos-business/${auth.businessId}${path}`,{...options,headers:{Authorization:`Bearer ${auth.token}`}});
 const can=p=>auth?.context.role==='OWNER'||auth?.context.permissions.includes(p);
 async function run(fn){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function signIn(e){e.preventDefault();await run(async()=>{const session=await storeApi('/pos-business/login',{body:{login:login.login,password:login.password}}),headers={Authorization:`Bearer ${session.token}`};const context=await storeApi(`/pos-business/${login.businessId}/context`,{headers}),workspace=await storeApi(`/pos-business/${login.businessId}/workspace`,{headers});setAuth({token:session.token,businessId:login.businessId,context});setData({'/workspace':workspace});setSection('home');setLogin(x=>({...x,password:''}));});}
 async function load(target=section){const jobs={home:['/workspace'],products:['/inventory'],customers:['/parties?kind=CUSTOMER'],suppliers:['/parties?kind=SUPPLIER'],finance:['/books','/activity'],debts:['/debts/aging?kind=AR','/debts/aging?kind=AP','/books'],reports:['/reports?period=MONTH','/customers/metrics','/online-report'],online:['/orders','/store'],users:['/users'],settings:['/store'],sell:['/products','/books']};await run(async()=>{const rows=await Promise.all((jobs[target]||[]).map(p=>call(p))),next=Object.fromEntries((jobs[target]||[]).map((p,i)=>[p,rows[i]]));setData(next);if(target==='settings')setForm({...auth.context.business,...rows[0].store});setSection(target);});}
 const submit=(path,body,notice,target=section)=>run(async()=>{await call(path,{body});setMessage(notice);setForm({});await load(target);});
 if(!auth)return <main className="merchant-app merchant-login"><section className="merchant-card"><span className="eyebrow">KlikPesantren POS</span><h1>Kelola usaha dari satu tempat</h1><p>Penjualan, stok, pelanggan, keuangan, dan toko online memakai satu sumber data.</p>{error&&<p role="alert" className="merchant-error">{error}</p>}<form onSubmit={signIn} className="merchant-form"><label>Login<input required value={login.login} onChange={e=>setLogin({...login,login:e.target.value})}/></label><label>Password<input required type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><label>ID bisnis<input required value={login.businessId} onChange={e=>setLogin({...login,businessId:e.target.value})}/></label><button>Masuk</button></form></section></main>;
 const nav=sections.filter(([, ,p])=>can(p));
 return <main className="merchant-app"><aside className="merchant-sidebar"><div><span className="eyebrow">{auth.context.role}</span><h2>{auth.context.business.display_name}</h2><small>{auth.context.business.ownership==='INTERNAL'?'Unit Usaha Internal':'Merchant Eksternal'}</small></div><nav>{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>load(id)}>{label}</button>)}</nav><button className="muted" onClick={()=>run(async()=>{await storeApi('/pos-business/logout',{body:{},headers:{Authorization:`Bearer ${auth.token}`}});setAuth(null);})}>Keluar</button></aside><div className="merchant-content"><header><div><span className="eyebrow">Workspace merchant</span><h1>{nav.find(x=>x[0]===section)?.[1]}</h1></div><button className="secondary" onClick={()=>load(section)}>Segarkan</button></header>{busy&&<p role="status">Memuat…</p>}{error&&<p role="alert" className="merchant-error">{error}</p>}{message&&<p role="status" className="merchant-success">{message}</p>}
  {section==='home'&&<Dashboard value={data['/workspace']}/>} {section==='products'&&<Products value={data['/inventory']} canEdit={can('products.manage')} form={form} setForm={setForm} submit={submit}/>} {section==='customers'&&<Parties title="Customer" rows={data['/parties?kind=CUSTOMER']||[]} kind="CUSTOMER" form={form} setForm={setForm} submit={submit}/>} {section==='suppliers'&&<Suppliers rows={data['/parties?kind=SUPPLIER']||[]} form={form} setForm={setForm} submit={submit}/>} {section==='finance'&&<Finance books={data['/books']} rows={data['/activity']||[]} form={form} setForm={setForm} submit={submit}/>} {section==='debts'&&<Debts ar={data['/debts/aging?kind=AR']} ap={data['/debts/aging?kind=AP']} books={data['/books']} form={form} setForm={setForm} submit={submit}/>} {section==='reports'&&<Reports report={data['/reports?period=MONTH']} customers={data['/customers/metrics']} online={data['/online-report']}/>} {section==='users'&&<Users rows={data['/users']||[]} form={form} setForm={setForm} submit={submit}/>} {section==='settings'&&<Settings form={form} setForm={setForm} submit={submit}/>} {section==='online'&&<Online rows={data['/orders']||[]} store={data['/store']}/>} {section==='sell'&&<Selling products={data['/products']||[]} books={data['/books']}/>} 
 </div></main>;
}
const Cards=({children})=><div className="merchant-grid">{children}</div>;const Card=({title,value,children})=><article className="merchant-card"><span>{title}</span>{value!=null&&<strong>{value}</strong>}{children}</article>;const Table=({rows=[],cols})=><div className="merchant-table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(([k,,render])=><td key={k}>{render?render(r[k],r):r[k]??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">Belum ada data.</p>}</div>;
function Dashboard({value}){if(!value)return null;const f=value.finance,a=value.attention;return <><Cards><Card title="Penjualan" value={rupiah(f?.sales||value.sales_today?.sales||0)}/><Card title="Laba kotor" value={f?rupiah(BigInt(f.sales)-BigInt(f.returns)-BigInt(f.cogs)):'Akses terbatas'}/><Card title="Transaksi" value={f?.transactions||value.sales_today?.transactions||0}/><Card title="Piutang" value={rupiah(a?.receivable||0)}/><Card title="Utang" value={rupiah(a?.payable||0)}/><Card title="Perlu perhatian" value={`${a?.low_stock||0} stok · ${a?.online_orders||0} order`}/></Cards><section className="merchant-panel"><h2>Kesiapan usaha</h2>{Object.entries(value.readiness||{}).map(([k,v])=><span className={`status ${v?'ok':''}`} key={k}>{k}: {v?'Siap':'Belum'}</span>)}</section></>}
function Products({value,canEdit,form,setForm,submit}){return <><Cards>{(value?.products||[]).slice(0,4).map(p=><Card key={p.id} title={p.name} value={`${p.available} tersedia`}><small>{p.category||'Tanpa kategori'} · {rupiah(p.selling_price)}</small></Card>)}</Cards><Table rows={value?.products} cols={[["name","Produk"],["category","Kategori"],["selling_price","Harga",rupiah],["on_hand","Stok"],["reserved","Dipesan"],["active","Status",v=>v?'Aktif':'Nonaktif']]}/>{canEdit&&<QuickForm title="Tambah produk" fields={['sku','name','category','uom','selling_price','minimum_stock']} form={form} setForm={setForm} onSubmit={()=>submit('/products',{...form,minimum_stock:form.minimum_stock||0},'Produk ditambahkan.','products')}/>}<section className="merchant-panel"><h2>Riwayat pergerakan</h2><Table rows={value?.movements} cols={[["created_at","Waktu",v=>new Date(v).toLocaleString('id-ID')],["name","Produk"],["kind","Jenis"],["quantity","Qty"],["reason","Alasan"],["cost","Nilai",v=>v==null?'Disembunyikan':rupiah(v)]]}/></section></>}
function Parties({title,rows,kind,form,setForm,submit}){return <><Table rows={rows} cols={[["name",title],["phone","Telepon"],["outstanding","Piutang",rupiah],["credit_limit","Limit",rupiah],["active","Status",v=>v?'Aktif':'Nonaktif']]}/><QuickForm title={`Tambah ${title}`} fields={['name','phone','address','notes','credit_limit','due_days']} form={form} setForm={setForm} onSubmit={()=>submit('/parties',{...form,kind,credit_allowed:kind==='CUSTOMER'&&!!form.credit_limit,credit_limit:form.credit_limit||0,due_days:form.due_days||0},`${title} ditambahkan.`)}/></>}
function Suppliers({rows,...rest}){return <><Parties title="Supplier" rows={rows} kind="SUPPLIER" {...rest}/><p className="note">Pembelian menambah stok melalui movement PURCHASE_IN; pembayaran utang lama tidak membuat pembelian baru.</p></>}
function Finance({books,rows,form,setForm,submit}){return <><Cards>{(books?.accounts||[]).map(a=><Card key={a.id} title={`${a.name} · ${a.kind}`} value={rupiah(a.balance)}/>)}</Cards><QuickForm title="Catat mutasi keuangan" fields={['kind','account_id','destination_account_id','amount','reason']} form={form} setForm={setForm} options={{kind:moneyKinds}} onSubmit={()=>submit('/money',{...form,request_id:uid()},'Mutasi ledger tersimpan.')}/><Table rows={rows} cols={[["created_at","Waktu",v=>new Date(v).toLocaleString('id-ID')],["kind","Klasifikasi"],["party","Pihak"],["total","Nominal",rupiah],["reason","Keterangan"]]}/><p className="note">Modal bukan pendapatan. Prive bukan biaya operasional. Wallet clearing bukan kas fisik.</p></>}
function Debts({ar,ap,form,setForm,submit}){return <><Cards><Card title="Total piutang" value={rupiah(ar?.outstanding||0)}/><Card title="Total utang" value={rupiah(ap?.outstanding||0)}/></Cards><h2>Piutang customer</h2><Table rows={ar?.items} cols={[["name","Customer"],["due_date","Jatuh tempo"],["days_overdue","Terlambat"],["outstanding","Outstanding",rupiah],["bucket","Aging"]]}/><h2>Utang supplier</h2><Table rows={ap?.items} cols={[["name","Supplier"],["due_date","Jatuh tempo"],["days_overdue","Terlambat"],["outstanding","Outstanding",rupiah],["bucket","Aging"]]}/><QuickForm title="Bayar / tagih utang-piutang" fields={['kind','source_id','account_id','amount']} form={form} setForm={setForm} options={{kind:[['AR','Terima piutang'],['AP','Bayar utang']]}} onSubmit={()=>submit('/debt-payments',{...form,request_id:uid()},'Pembayaran dicatat tanpa menduplikasi transaksi.')}/></>}
function Reports({report,customers,online}){return <><Cards><Card title="Penjualan" value={rupiah(report?.kpi?.sales||0)}/><Card title="HPP" value={rupiah(report?.kpi?.cogs||0)}/><Card title="Hasil operasional" value={rupiah(report?.kpi?.operating_result||0)}/><Card title="Online order" value={online?.order_count||0}/></Cards><p className="note">{report?.formula}</p><Table rows={customers?.customers?.slice(0,20)} cols={[["name","Customer"],["net_spend","Belanja neto",rupiah],["transaction_count","Transaksi"],["average_transaction","Rata-rata",rupiah],["pos_spend","POS",rupiah],["online_spend","Online",rupiah]]}/></>}
function Users({rows,form,setForm,submit}){return <><Table rows={rows} cols={[["name","Nama"],["login","Login"],["role","Role"],["permissions","Permission",v=>(v||[]).join(', ')||'Default role'],["membership_active","Status",v=>v?'Aktif':'Nonaktif']]}/><QuickForm title="Tambah pengguna" fields={['login','name','password','role','permissions']} form={form} setForm={setForm} options={{role:[['OWNER','Owner'],['SUPERVISOR','Supervisor'],['CASHIER','Cashier']]}} onSubmit={()=>submit('/users',{...form,permissions:form.role==='SUPERVISOR'?String(form.permissions||'').split(',').map(x=>x.trim()).filter(Boolean):[]},'Pengguna dibuat.')}/></>}
function Settings({form,setForm,submit}){return <QuickForm title="Profil, branding & struk" fields={['display_name','legal_name','description','address','phone','logo_url','banner_url','brand_color','receipt_name','receipt_header','receipt_footer','receipt_prefix','timezone']} form={form} setForm={setForm} onSubmit={()=>submit('/profile',{...form,receipt_logo:!!form.logo_url},'Profil bisnis tersimpan.','settings')}/>}
function Online({rows,store}){return <><Cards><Card title="Status toko" value={store?.store?.storefront_enabled?'Aktif':'Nonaktif'}/><Card title="Slug" value={store?.store?.storefront_slug||'Belum diatur'}/><Card title="Pesanan masuk" value={rows.length}/></Cards>{store?.store?.storefront_slug&&<a className="merchant-link" href={`/store/${store.store.storefront_slug}`}>Lihat toko</a>}<Table rows={rows} cols={[["order_number","Pesanan"],["recipient","Customer"],["fulfillment","Pemenuhan"],["payment_state","Pembayaran"],["status","Status"],["total","Total",rupiah]]}/><p className="note">Kelola status, kurir, resi, branding, dan produk online lengkap tersedia pada halaman Toko Online.</p></>}
function Selling({products,books}){return <><section className="merchant-panel"><h2>Mulai penjualan</h2><p>Gunakan aplikasi POS kasir untuk cart, pembayaran tunai/bank/QRIS/Dompet Santri/piutang, dan struk. Semua harga dan saldo diverifikasi server.</p></section><Table rows={products} cols={[["name","Produk"],["available","Tersedia"],["selling_price","Harga",rupiah]]}/><Cards>{(books?.accounts||[]).filter(a=>a.kind==='CASH').map(a=><Card key={a.id} title={`Laci ${a.name}`} value={rupiah(a.balance)}/>)}</Cards></>}
function QuickForm({title,fields,form,setForm,onSubmit,options={}}){return <form className="merchant-panel merchant-form" onSubmit={e=>{e.preventDefault();onSubmit();}}><h2>{title}</h2><div className="form-grid">{fields.map(k=><label key={k}>{k.replaceAll('_',' ')}{options[k]?<select required value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">Pilih</option>{options[k].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input required={!['legal_name','description','address','phone','logo_url','banner_url','brand_color','receipt_header','receipt_footer','destination_account_id','category','notes','permissions'].includes(k)} type={k==='password'?'password':'text'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</div><button>Simpan</button></form>}
