const STATUS = new Set(["H", "I", "S", "A"]);
const SOURCE = new Set(["admin", "manual", "device", "system"]);
const MAX_OFFLINE_AGE_MS = 7 * 24 * 60 * 60 * 1000;

function policyError(code, message) {
  const error = new Error(message);
  error.code = code;
  error.status = 409;
  return error;
}

function asDate(value, field) {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) throw policyError("INVALID_" + field.toUpperCase(), field + " tidak valid");
  return date;
}

function decideAttendanceTransition({
  current = null,
  nextStatus,
  source,
  adminExplicit = false,
  capturedAt = null,
  receivedAt = null,
  windowStart = null,
  windowEnd = null,
  occurrenceState = "active",
}) {
  if (!STATUS.has(nextStatus)) throw policyError("INVALID_ATTENDANCE_STATUS", "Status absensi tidak valid");
  if (!SOURCE.has(source)) throw policyError("INVALID_ATTENDANCE_SOURCE", "Sumber absensi tidak valid");

  if (source === "admin" || source === "manual") {
    if (!adminExplicit) return { allowed: false, changed: false, code: "ADMIN_EXPLICIT_REQUIRED" };
    return {
      allowed: true,
      changed: !current || current.status !== nextStatus || !current.protected_manual,
      code: "ADMIN_CORRECTION",
      protectedManual: true,
      autoGenerated: false,
    };
  }

  if (source === "system") {
    if (nextStatus !== "A") return { allowed: false, changed: false, code: "SYSTEM_ONLY_AUTO_ALFA" };
    if (current) return { allowed: true, changed: false, code: "RESULT_ALREADY_EXISTS" };
    return { allowed: true, changed: true, code: "AUTO_ALFA", protectedManual: false, autoGenerated: true };
  }

  if (nextStatus !== "H") return { allowed: false, changed: false, code: "DEVICE_ONLY_HADIR" };
  if (occurrenceState === "cancelled") return { allowed: false, changed: false, code: "OCCURRENCE_CANCELLED" };

  const captured = asDate(capturedAt, "captured_at");
  const received = asDate(receivedAt, "received_at");
  const start = asDate(windowStart, "window_start");
  const end = asDate(windowEnd, "window_end");
  if (captured < start || captured >= end) {
    return { allowed: false, changed: false, code: "OUTSIDE_ATTENDANCE_WINDOW" };
  }
  const age = received.getTime() - captured.getTime();
  if (age < 0 || age > MAX_OFFLINE_AGE_MS) {
    return { allowed: false, changed: false, code: "EVENT_OUTSIDE_OFFLINE_POLICY" };
  }

  if (!current) return { allowed: true, changed: true, code: "DEVICE_HADIR", protectedManual: false, autoGenerated: false };
  if (current.protected_manual || current.source === "admin" || current.source === "manual") {
    return { allowed: false, changed: false, code: "MANUAL_RESULT_PROTECTED" };
  }
  if (current.status === "I") return { allowed: false, changed: false, code: "IZIN_PROTECTED" };
  if (current.status === "S") return { allowed: false, changed: false, code: "SAKIT_PROTECTED" };
  if (current.status === "H") return { allowed: true, changed: false, code: "ALREADY_HADIR" };
  if (current.status === "A" && current.auto_generated) {
    return { allowed: true, changed: true, code: "LATE_HADIR_RECONCILED", protectedManual: false, autoGenerated: false };
  }
  return { allowed: false, changed: false, code: "EXISTING_RESULT_PROTECTED" };
}

module.exports = {
  MAX_OFFLINE_AGE_MS,
  decideAttendanceTransition,
  policyError,
};
