const {productImageUrl}=require('../utils/posProductImage');
function createBusinessWorkspace({run,bad,uuid,amount,text}){
 const optional=(v,max)=>v==null||String(v).trim()===''?null:text(String(v),max);
 const permitted=(a,p)=>a.member.role==='OWNER'||(a.member.role==='SUPERVISOR'&&a.member.permissions.includes(p));
 async function workspace(req){return run(req,'profile.read',async(c,a)=>{const privileged=permitted(a,'reports.read'),operational=a.member.role==='CASHIER'||permitted(a,'sale.post');
  const readiness=(await c.query(`SELECT (display_name<>'' AND timezone<>'' AND currency='IDR') profile,EXISTS(SELECT 1 FROM pos_business_accounts WHERE business_id=$1 AND active) account,EXISTS(SELECT 1 FROM pos_business_terminals WHERE business_id=$1 AND active) terminal,EXISTS(SELECT 1 FROM pos_business_products WHERE business_id=$1 AND active) product,storefront_enabled,storefront_slug FROM pos_businesses WHERE id=$1`,[a.business])).rows[0];
  const out={role:a.member.role,readiness,open_shift:(await c.query("SELECT id,terminal_id,cash_account_id,opening_cash,opened_at FROM pos_business_shifts WHERE business_id=$1 AND user_id=$2 AND status='OPEN'",[a.business,a.user])).rows[0]||null};
  if(operational)out.sales_today=(await c.query("SELECT count(*) transactions,coalesce(sum(total),0) sales FROM pos_business_operations WHERE business_id=$1 AND kind='SALE' AND (created_at AT TIME ZONE $2)::date=(now() AT TIME ZONE $2)::date",[a.business,a.member.timezone])).rows[0];
  if(privileged){out.finance=(await c.query(`SELECT coalesce(sum(total) FILTER(WHERE kind='SALE'),0) sales,coalesce(sum(total) FILTER(WHERE kind='SALE_RETURN'),0) returns,coalesce(sum((SELECT coalesce(sum(cogs),0) FROM pos_business_lines l WHERE l.operation_id=o.id)) FILTER(WHERE kind='SALE'),0) cogs,count(*) FILTER(WHERE kind='SALE') transactions FROM pos_business_operations o WHERE business_id=$1`,[a.business])).rows[0];out.attention=(await c.query(`SELECT (SELECT count(*) FROM pos_business_products p LEFT JOIN(SELECT product_id,sum(quantity) q FROM pos_inventory_movements WHERE business_id=$1 GROUP BY product_id)s ON s.product_id=p.id WHERE p.business_id=$1 AND coalesce(s.q,0)<=p.minimum_stock) low_stock,(SELECT count(*) FROM pos_online_orders WHERE business_id=$1 AND status IN('ORDERED','CONFIRMED','PROCESSING','READY_TO_SHIP')) online_orders,(SELECT coalesce(sum(amount),0) FROM pos_debt_movements WHERE business_id=$1 AND kind='AR') receivable,(SELECT coalesce(sum(amount),0) FROM pos_debt_movements WHERE business_id=$1 AND kind='AP') payable`,[a.business])).rows[0];}
  return out;});}
 async function profile(req){return run(req,'profile.manage',async(c,a)=>{const b=req.body||{},color=b.brand_color||null;if(color&&!/^#[0-9a-f]{6}$/i.test(color))bad('INVALID_BRAND_COLOR');return (await c.query(`UPDATE pos_businesses SET display_name=$1,legal_name=$2,description=$3,address=$4,phone=$5,logo_url=$6,banner_url=$7,brand_color=$8,receipt_name=$9,receipt_header=$10,receipt_footer=$11,receipt_logo=$12,receipt_prefix=$13,timezone=$14 WHERE id=$15 RETURNING id,display_name,ownership,timezone,currency`,[text(b.display_name),optional(b.legal_name,160),optional(b.description,500),optional(b.address,1000),optional(b.phone,80),productImageUrl(b.logo_url),productImageUrl(b.banner_url),color,optional(b.receipt_name,160),optional(b.receipt_header,300),optional(b.receipt_footer,300),b.receipt_logo===true,text(b.receipt_prefix,16).toUpperCase(),text(b.timezone,80),a.business])).rows[0];});}
 async function members(req){return run(req,'users.manage',async(c,a)=>(await c.query(`SELECT u.id,u.login,u.name,u.active user_active,m.role,m.permissions,m.active membership_active,u.created_at FROM pos_merchant_memberships m JOIN pos_merchant_users u ON u.id=m.user_id WHERE m.business_id=$1 ORDER BY m.role,u.name`,[a.business])).rows);}
 async function updateMember(req){return run(req,'users.manage',async(c,a)=>{if(a.member.role!=='OWNER')bad('OWNER_REQUIRED',403);const id=uuid(req.params.userId),b=req.body||{};if(id===a.user&&b.active===false)bad('SELF_DEACTIVATION_DENIED',409);if(!['OWNER','SUPERVISOR','CASHIER'].includes(b.role))bad('INVALID_ROLE');const permissions=b.permissions||[];if(!Array.isArray(permissions)||b.role!=='SUPERVISOR'&&permissions.length)bad('INVALID_PERMISSIONS');const row=(await c.query('UPDATE pos_merchant_memberships SET role=$1,permissions=$2,active=$3 WHERE business_id=$4 AND user_id=$5 RETURNING user_id,role,permissions,active',[b.role,permissions,b.active!==false,a.business,id])).rows[0];if(!row)bad('MEMBER_NOT_FOUND',404);return row;});}
 async function directory(req){const kind=req.query?.kind||'CUSTOMER',permission=kind==='SUPPLIER'?'purchases.post':'customers.read';if(!['CUSTOMER','SUPPLIER'].includes(kind))bad('INVALID_PARTY_KIND');return run(req,permission,async(c,a)=>(await c.query(`SELECT p.id,p.kind,p.name,p.phone,p.address,p.notes,p.active,p.credit_allowed,p.credit_limit,p.due_days,coalesce(d.outstanding,0) outstanding FROM pos_business_parties p LEFT JOIN(SELECT party_id,sum(amount) outstanding FROM pos_debt_movements WHERE business_id=$1 GROUP BY party_id)d ON d.party_id=p.id WHERE p.business_id=$1 AND p.kind=$2 ORDER BY p.active DESC,p.name LIMIT 300`,[a.business,kind])).rows);}
 async function inventory(req){return run(req,'products.read',async(c,a)=>{const costs=permitted(a,'reports.read')||permitted(a,'purchases.post');const products=(await c.query(`SELECT p.*,coalesce(s.on_hand,0) on_hand,coalesce(r.reserved,0) reserved,coalesce(s.on_hand,0)-coalesce(r.reserved,0) available FROM pos_business_products p LEFT JOIN(SELECT product_id,sum(quantity) on_hand FROM pos_inventory_movements WHERE business_id=$1 GROUP BY product_id)s ON s.product_id=p.id LEFT JOIN(SELECT product_id,sum(quantity) reserved FROM pos_online_reservations WHERE business_id=$1 AND state='RESERVED' GROUP BY product_id)r ON r.product_id=p.id WHERE p.business_id=$1 ORDER BY p.name LIMIT 300`,[a.business])).rows;const movements=(await c.query(`SELECT m.id,m.product_id,p.name,m.quantity,m.kind,m.reason,m.created_at,${costs?'m.cost':'NULL::bigint'} cost FROM pos_inventory_movements m JOIN pos_business_products p ON p.id=m.product_id WHERE m.business_id=$1 ORDER BY m.created_at DESC,m.id LIMIT 200`,[a.business])).rows;return {products,movements,cost_visible:costs};});}
 async function activity(req){return run(req,'reports.read',async(c,a)=>(await c.query(`SELECT o.id,o.kind,o.channel,o.total,o.paid,o.due_date,o.reference,o.reason,o.created_at,p.name party FROM pos_business_operations o LEFT JOIN pos_business_parties p ON p.id=o.party_id WHERE o.business_id=$1 ORDER BY o.created_at DESC,o.id LIMIT 300`,[a.business])).rows);}
 async function updateProduct(req){return run(req,'products.manage',async(c,a)=>{const b=req.body||{},id=uuid(req.params.productId);const row=(await c.query(`UPDATE pos_business_products SET name=$1,category=$2,uom=$3,image_url=$4,selling_price=$5,minimum_stock=$6,active=$7,sellable=$8 WHERE id=$9 AND business_id=$10 RETURNING id,name,selling_price`,[text(b.name),optional(b.category,120),optional(b.uom,32)||'pcs',productImageUrl(b.image_url),amount(b.selling_price,true).toString(),amount(b.minimum_stock||0).toString(),b.active!==false,b.sellable!==false,id,a.business])).rows[0];if(!row)bad('PRODUCT_NOT_FOUND',404);return row;});}
 return {workspace,profile,members,updateMember,directory,inventory,activity,updateProduct};
}
module.exports={createBusinessWorkspace};
