// Exact normal-runtime database privileges for POS V1/V2.
// Environment-specific role names deliberately do not belong in this manifest.
const tables = {
  pos_business_accounts: { select: true, insert: true, update: ["id"] },
  pos_business_admin_audit: { select: true, insert: true },
  pos_business_lines: { select: true, insert: true },
  pos_business_operations: { select: true, insert: true },
  pos_business_parties: { select: true, insert: true, update: ["name", "phone", "address", "notes", "active", "credit_allowed", "credit_limit", "due_days"] },
  pos_business_payments: { select: true, insert: true },
  pos_business_products: { select: true, insert: true, update: ["name", "category", "uom", "image_url", "selling_price", "minimum_stock", "active", "sellable", "online_visible", "online_price", "online_description", "online_long_description", "online_featured", "online_sort"] },
  pos_business_provision_requests: { select: true, insert: true },
  pos_business_shifts: { select: true, insert: true, update: ["status", "closed_at", "actual_cash", "expected_cash", "difference"] },
  pos_business_terminals: { select: true, insert: true, update: ["id"] },
  pos_business_units: { select: true, insert: true },
  pos_business_wallet_links: { select: true, insert: true },
  pos_businesses: { select: true, insert: true, update: ["display_name", "legal_name", "description", "address", "phone", "logo_url", "banner_url", "brand_color", "receipt_name", "receipt_header", "receipt_footer", "receipt_logo", "receipt_prefix", "timezone", "accounting_start_date", "storefront_slug", "storefront_enabled", "public_phone", "hours_text", "storefront_footer", "shipping_charge", "reservation_minutes", "payment_instructions", "active", "integration_enabled", "wallet_enabled"] },
  pos_cashier_assignments: { select: true, insert: true, update: ["active"] },
  pos_categories: { select: true, insert: true, update: ["name", "active"] },
  pos_debt_movements: { select: true, insert: true },
  pos_inventory_allocations: { select: true, insert: true },
  pos_inventory_layers: { select: true, insert: true },
  pos_inventory_movements: { select: true, insert: true },
  pos_merchant_activation_tokens: { select: true, insert: true, update: ["token_hash", "expires_at", "created_by", "created_at"], delete: true },
  pos_merchant_login_limits: { select: true, insert: true, update: ["attempts", "started_at"] },
  pos_merchant_memberships: { select: true, insert: true, update: ["role", "permissions", "active"] },
  pos_merchant_permission_audit: { insert: true },
  pos_merchant_sessions: { select: true, insert: true, delete: true },
  pos_merchant_users: { select: true, insert: true, update: ["name", "password_hash"] },
  pos_money_movements: { select: true, insert: true },
  pos_online_customer_access: { select: true, insert: true, update: ["active"] },
  pos_online_order_events: { select: true, insert: true },
  pos_online_order_lines: { select: true, insert: true },
  pos_online_orders: { select: true, insert: true, update: ["status", "payment_state", "sale_id", "shipping_operation_id", "shipping_refund_id", "courier", "tracking", "updated_at", "shipped_at"] },
  pos_online_request_limits: { select: true, insert: true, update: ["attempts", "started_at"] },
  pos_online_reservations: { select: true, insert: true, update: ["state"] },
  pos_payments: { select: true, insert: true, update: ["status", "external_reference", "verified_by", "verified_at"] },
  pos_products: { select: true, insert: true, update: ["category_id", "sku", "name", "price", "active", "available", "image_url", "updated_at"] },
  pos_refunds: { select: true, insert: true, update: ["status", "external_reference", "confirmed_by", "confirmed_at"] },
  pos_sale_items: { select: true, insert: true },
  pos_sales: { select: true, insert: true, update: ["status", "void_reason", "void_by", "void_at"] },
  pos_shifts: { select: true, insert: true, update: ["status", "closed_at", "closed_by", "expected_cash", "actual_cash", "difference"] },
  pos_wallet_credential_audits: { insert: true },
  pos_wallet_credentials: { select: true, insert: true, update: ["active", "revoked_at"] },
};

module.exports = Object.freeze({ schema: "public", tables: Object.freeze(tables), sequences: Object.freeze([]) });
